/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitterhashtagstorm;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SANDY
 */
public class TwitterApp extends javax.swing.JFrame {

    /**
     * Creates new form TwitterApp
     */
    DefaultTableModel dtm = new DefaultTableModel();
    FileReader reader;
    BufferedReader bufferedReader;

    public TwitterApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic_search_pane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        detailed_table = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        tag_table = new javax.swing.JScrollPane();
        top_tags_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        keyword_label = new javax.swing.JLabel();
        keyword_textfield = new javax.swing.JTextField();
        separator = new javax.swing.JSeparator();
        duration = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        noof_tweets_lbl = new javax.swing.JLabel();
        noof_tweets_count_lbl = new javax.swing.JLabel();
        noof_tags_lbl = new javax.swing.JLabel();
        noof_tags_count_lbl = new javax.swing.JLabel();
        menu_bar = new javax.swing.JMenuBar();
        file_menu = new javax.swing.JMenu();
        exit_menu_item = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Twitter # Tag Application");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/twitterhashtagstorm/icon.png")).getImage());

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Hashtag (#)", "Display Name", "Username", "Time", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        data_table.getTableHeader().setReorderingAllowed(false);
        detailed_table.setViewportView(data_table);
        if (data_table.getColumnModel().getColumnCount() > 0) {
            data_table.getColumnModel().getColumn(0).setResizable(false);
            data_table.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        top_tags_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No", "Hashtag (#)", "# of Times Used"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        top_tags_table.getTableHeader().setReorderingAllowed(false);
        tag_table.setViewportView(top_tags_table);
        if (top_tags_table.getColumnModel().getColumnCount() > 0) {
            top_tags_table.getColumnModel().getColumn(0).setPreferredWidth(1);
        }

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        keyword_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        keyword_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        keyword_label.setText("Enter Keyword");

        keyword_textfield.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        keyword_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        keyword_textfield.setName(""); // NOI18N

        duration.setBackground(new java.awt.Color(204, 204, 204));
        duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "5", "10", "15", "30", "45", "60" }));
        duration.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Running Time in Mins", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        duration.setName(""); // NOI18N

        search_btn.setBackground(new java.awt.Color(0, 153, 0));
        search_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search_btn.setText("Search # Tags");
        search_btn.setFocusPainted(false);
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(keyword_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keyword_textfield)
                    .addComponent(separator, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duration, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keyword_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(keyword_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addContainerGap())
        );

        noof_tweets_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noof_tweets_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noof_tweets_lbl.setText("Total No. of Tweets");

        noof_tweets_count_lbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        noof_tweets_count_lbl.setForeground(new java.awt.Color(0, 102, 0));
        noof_tweets_count_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noof_tweets_count_lbl.setText("0");

        noof_tags_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        noof_tags_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noof_tags_lbl.setText("No. of # Tags used");

        noof_tags_count_lbl.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        noof_tags_count_lbl.setForeground(new java.awt.Color(255, 0, 0));
        noof_tags_count_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noof_tags_count_lbl.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailed_table)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noof_tweets_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noof_tweets_count_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noof_tags_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noof_tags_count_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tag_table, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(noof_tweets_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noof_tweets_count_lbl)
                        .addGap(18, 18, 18)
                        .addComponent(noof_tags_lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(noof_tags_count_lbl))
                    .addComponent(tag_table, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailed_table, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addContainerGap())
        );

        topic_search_pane.addTab("Topic Search", jPanel2);

        file_menu.setText("File");

        exit_menu_item.setIcon(new javax.swing.ImageIcon(getClass().getResource("/twitterhashtagstorm/exit_icon.png"))); // NOI18N
        exit_menu_item.setText("Exit");
        exit_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menu_itemActionPerformed(evt);
            }
        });
        file_menu.add(exit_menu_item);

        menu_bar.add(file_menu);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topic_search_pane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(topic_search_pane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exit_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menu_itemActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exit_menu_itemActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) data_table.getModel();
        DefaultTableModel rdtm = (DefaultTableModel) top_tags_table.getModel();
        data_table.setModel(dtm);
        top_tags_table.setModel(rdtm);
        TwitterHashtagStorm ths = new TwitterHashtagStorm();
        ths.keyword = keyword_textfield.getText();
        long temptime = Long.parseLong((String) duration.getSelectedItem());
        ths.time = temptime * 60000;
        try {
            Thread.sleep(2000);
            ths.initSetup();// TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(TwitterApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        while (dtm.getRowCount() > 0) {
            for (int i = 0; i < dtm.getRowCount(); i++) {
                dtm.removeRow(i);
            }
        }
        while (rdtm.getRowCount() > 0) {
            for (int i = 0; i < rdtm.getRowCount(); i++) {
                rdtm.removeRow(i);
            }
        }
        try {
            reader = new FileReader("twittertags.dat");
            bufferedReader = new BufferedReader(reader);
            String line;
            int i = 1;
            while ((line = bufferedReader.readLine()) != null) {
                String[] lineValue = line.split("\t");
                dtm.addRow(new Object[]{i, lineValue[0], lineValue[1], lineValue[2], lineValue[3], lineValue[4]});
                noof_tweets_count_lbl.setText("" + i);
                i++;
            }
            reader.close();
            File f = new File("twittertags.dat");
            f.delete();
            //Result
            reader = new FileReader("twitterresult.dat");
            bufferedReader = new BufferedReader(reader);
            String rline;
            int ri = 1;
            while ((rline = bufferedReader.readLine()) != null) {
                String[] lineValue = rline.split("\t");
                rdtm.addRow(new Object[]{ri, lineValue[0], Integer.parseInt(lineValue[1])});
                noof_tags_count_lbl.setText("" + ri);
                ri++;
            }
            top_tags_table.setAutoCreateRowSorter(true);
            reader.close();
            File rf = new File("twitterresult.dat");
            rf.delete();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable data_table;
    private javax.swing.JScrollPane detailed_table;
    private javax.swing.JComboBox<String> duration;
    private javax.swing.JMenuItem exit_menu_item;
    private javax.swing.JMenu file_menu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel keyword_label;
    private javax.swing.JTextField keyword_textfield;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JLabel noof_tags_count_lbl;
    private javax.swing.JLabel noof_tags_lbl;
    private javax.swing.JLabel noof_tweets_count_lbl;
    private javax.swing.JLabel noof_tweets_lbl;
    private javax.swing.JButton search_btn;
    private javax.swing.JSeparator separator;
    private javax.swing.JScrollPane tag_table;
    private javax.swing.JTable top_tags_table;
    private javax.swing.JTabbedPane topic_search_pane;
    // End of variables declaration//GEN-END:variables
}
